apiVersion: v1
kind: Service
metadata:
  name: sathya-mysql-service
  namespace: batch2
spec:
  selector:
    app: sql-app
    tier: backend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: http